use_frameworks!
platform :ios, '11.0'
target 'HJWeather_Example' do
  pod 'HJWeather', :path => '../'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'HJWeather_Tests' do
    inherit! :search_paths

    
  end
end
